// js/products.js
// Product catalogue (SKU + carton dimensions) and the lookup service the UI talks to.
//
// The catalogue currently ships as bundled sample data. The eventual source is
// Plytix (PIM) — exported server-side to a static products.json on a schedule,
// so no credentials or per-keystroke API calls ever reach the browser.
// When that lands, only `Products.load()` below changes; nothing else in the app
// touches the data directly.

window.CartonApp = window.CartonApp || {};

// -------------------------------------------------
// Sample catalogue — same envelope shape the generated products.json will use
// -------------------------------------------------
window.CartonApp.SAMPLE_CATALOGUE = {
  generated: "2026-09-04T06:00:00Z",
  source: "sample",
  products: [
    {
      sku: "488881",
      name: "10.5 Tog Duvet — Single",
      carton: { l: 600, w: 400, h: 320, weight: 9.6 },
      innersPerCarton: 4,
    },
    {
      sku: "488882",
      name: "10.5 Tog Duvet — Double",
      carton: { l: 700, w: 450, h: 350, weight: 12.4 },
      innersPerCarton: 4,
    },
    {
      sku: "488883",
      name: "10.5 Tog Duvet — King",
      carton: { l: 750, w: 500, h: 380, weight: 14.8 },
      innersPerCarton: 4,
    },
    {
      sku: "488884",
      name: "13.5 Tog Duvet — Double",
      carton: { l: 700, w: 450, h: 420, weight: 15.2 },
      innersPerCarton: 4,
    },
    {
      sku: "488885",
      name: "Hollowfibre Pillow — Standard",
      carton: { l: 800, w: 450, h: 400, weight: 7.2 },
      innersPerCarton: 8,
    },
    {
      sku: "488886",
      name: "Memory Foam Pillow — Standard",
      carton: { l: 650, w: 400, h: 300, weight: 11.5 },
      innersPerCarton: 6,
    },
    {
      sku: "488887",
      name: "Quilted Mattress Protector — Double",
      carton: { l: 400, w: 300, h: 250, weight: 8.4 },
      innersPerCarton: 10,
    },
    {
      sku: "488888",
      name: "Quilted Mattress Protector — King",
      carton: { l: 450, w: 300, h: 280, weight: 9.9 },
      innersPerCarton: 10,
    },
    {
      sku: "488889",
      name: "Memory Foam Mattress Topper — Double",
      carton: { l: 900, w: 400, h: 400, weight: 18.6 },
      innersPerCarton: 1,
    },
    {
      sku: "488890",
      name: "Fitted Sheet 200TC — Double",
      carton: { l: 500, w: 350, h: 300, weight: 6.8 },
      innersPerCarton: 12,
    },
    {
      sku: "488891",
      name: "Duvet Cover Set — Double",
      carton: { l: 550, w: 380, h: 330, weight: 10.2 },
      innersPerCarton: 8,
    },
    {
      sku: "488892",
      name: "Fleece Throw Blanket — 150×200",
      carton: { l: 600, w: 400, h: 450, weight: 13.0 },
      innersPerCarton: 10,
    },
  ],
};

// -------------------------------------------------
// Products service — the single seam between the UI and the data source
// -------------------------------------------------
window.CartonApp.Products = {
  _cache: null,

  // Resolves to an array of products.
  //
  // Swap the body for a fetch when products.json goes live:
  //   const res = await fetch("/data/products.json");
  //   const json = await res.json();
  //   return json.products;
  // A rejection here is expected to be survivable — the UI falls back to
  // manual entry, which is how the tool works today.
  // Generated by api/export-products.php from Plytix. Same-origin, so it is
  // permitted by the page's connect-src 'self' CSP without any change.
  CATALOGUE_URL: "/data/products.json",

  load: function () {
    if (this._cache) return Promise.resolve(this._cache);
    const self = this;

    return fetch(this.CATALOGUE_URL, { cache: "no-cache" })
      .then(function (res) {
        if (!res.ok) throw new Error("HTTP " + res.status);
        return res.json();
      })
      .then(function (json) {
        const list = (json && json.products) || [];
        if (!list.length) throw new Error("catalogue is empty");
        self._meta = {
          generated: json.generated || null,
          source: json.source || "plytix",
        };
        self._cache = list;
        self._warnOnDuplicateSkus(list);
        return list;
      })
      .catch(function (err) {
        // Silently substituting sample data in production would let people
        // plan pallets against SKUs that do not exist, so the fallback is
        // limited to local development.
        if (!self._sampleAllowed()) throw err;
        console.warn(
          "Product catalogue unavailable (" + err.message + "); using bundled sample data."
        );
        const catalogue = window.CartonApp.SAMPLE_CATALOGUE || {};
        self._meta = { generated: catalogue.generated || null, source: "sample" };
        self._cache = catalogue.products || [];
        self._warnOnDuplicateSkus(self._cache);
        return self._cache;
      });
  },

  _sampleAllowed: function () {
    if (window.CartonApp.USE_SAMPLE_CATALOGUE === true) return true;
    const h = window.location.hostname;
    return h === "localhost" || h === "127.0.0.1" || h === "";
  },

  // Lookups are case-insensitive, so two catalogue entries differing only by
  // case would collide and one would become unreachable. Cheap to check here,
  // and it is the Plytix export that would need fixing rather than this code.
  _warnOnDuplicateSkus: function (products) {
    const seen = new Map();
    const dupes = [];
    products.forEach((p) => {
      const key = String(p.sku).trim().toLowerCase();
      if (seen.has(key)) dupes.push(`${seen.get(key)} / ${p.sku}`);
      else seen.set(key, p.sku);
    });
    if (dupes.length) {
      console.warn(
        "Product catalogue contains SKUs that collide case-insensitively:",
        dupes
      );
    }
  },

  // Catalogue metadata (generated timestamp, source) for display.
  _meta: null,
  meta: function () {
    return this._meta || { generated: null, source: "unknown" };
  },

  findBySku: function (products, sku) {
    if (!sku) return null;
    const needle = String(sku).trim().toLowerCase();
    return products.find((p) => p.sku.toLowerCase() === needle) || null;
  },

  // Token search across sku + name, so "duvet double" matches
  // "10.5 Tog Duvet — Double". Every token must appear somewhere.
  search: function (products, query) {
    const q = (query || "").trim().toLowerCase();
    if (!q) return products;
    const tokens = q.split(/\s+/);
    return products.filter((p) => {
      const haystack = `${p.sku} ${p.name}`.toLowerCase();
      return tokens.every((t) => haystack.includes(t));
    });
  },

  // Has the user hand-adjusted any dimension away from the catalogue value?
  // Drives the "adjusted" badge so an edited SKU never silently reads as stock.
  isAdjusted: function (product, carton) {
    if (!product || !carton) return false;
    const c = product.carton || {};
    return (
      Number(carton.l) !== Number(c.l) ||
      Number(carton.w) !== Number(c.w) ||
      Number(carton.h) !== Number(c.h) ||
      Number(carton.weight) !== Number(c.weight) ||
      Number(carton.innersPerCarton || 0) !== Number(product.innersPerCarton || 0)
    );
  },

  // Tolerant lookup for spreadsheet cells.
  //
  // Excel silently coerces SKU cells that look numeric: "0056" arrives as 56,
  // and "5642E10" as 56420000000000. Rather than trying to un-mangle the cell,
  // compare in the other direction — what would Excel have done to each
  // catalogue SKU? Only runs once an exact match has already failed, and
  // refuses to guess when more than one candidate collides.
  resolveSku: function (products, raw) {
    const value = String(raw == null ? "" : raw).trim();
    if (!value) return { product: null, status: "" };

    const exact = this.findBySku(products, value);
    if (exact) return { product: exact, status: "" };

    const asNumber = Number(value);
    if (!isNaN(asNumber)) {
      const collisions = products.filter((p) => {
        const n = Number(String(p.sku).trim());
        return !isNaN(n) && n === asNumber;
      });
      if (collisions.length === 1) {
        return { product: collisions[0], status: "MATCHED — CHECK CELL FORMAT" };
      }
      if (collisions.length > 1) return { product: null, status: "AMBIGUOUS" };
    }

    return { product: null, status: "NOT FOUND" };
  },

  // Product → the shape the carton state expects.
  toCarton: function (product) {
    const c = product.carton || {};
    return {
      l: Number(c.l) || 0,
      w: Number(c.w) || 0,
      h: Number(c.h) || 0,
      weight: Number(c.weight) || 0,
      innersPerCarton: Number(product.innersPerCarton) || 0,
    };
  },
};
